server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/restaurant_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: ${secrets.DB_USERNAME}
    password: ${secrets.DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update # 'update' para desarrollo, 'none' para producción. 'create-drop' para pruebas.
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
  auth:
    service:
      host: http://localhost:8081
      url: /api/v1/users/isOwner